# Generated by Django 3.1.4 on 2021-01-03 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victims', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='victim',
            name='published_date',
        ),
        migrations.AddField(
            model_name='victim',
            name='address',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='victim',
            name='birthdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='victim',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (0, 'Female')], default=1),
        ),
        migrations.AlterField(
            model_name='victim',
            name='firstname',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='victim',
            name='lastname',
            field=models.CharField(default='', max_length=40),
        ),
    ]
