# Generated by Django 3.1.4 on 2021-01-03 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201231_1735'),
        ('victims', '0002_auto_20210103_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='id_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
