# Generated by Django 3.1.4 on 2021-01-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victims', '0004_victim_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='is_complete',
            field=models.IntegerField(choices=[(1, 'Complete'), (0, 'Not complete')], default=0),
        ),
    ]
